### ISSUE TITLE
Red screen of death

### ISSUE THREAD

**Issue by bahaafathi** [jesusrp98/spacex-go#132]
**i hope to assigned this bug to me and accept my pull request to this great beautiful app, Thanks.**
<img width="479" alt="Screen Shot 2021-04-29 at 2 08 32 AM" src="https://user-images.githubusercontent.com/35146824/116497570-006c4600-a8a8-11eb-8437-80a79b92c55e.png">
<img width="479" alt="Screen Shot 2021-04-29 at 2 12 20 AM" src="https://user-images.githubusercontent.com/35146824/116497586-082bea80-a8a8-11eb-849a-3cb84541a2ed.png">

**Comment by jesusrp98** [comment]
Hey @bahaafathi! Thank you very much for the support and for taking the time to find bugs!

I've read the fix you've done in your PR, but I don't think it's optimal, because displaying empty data on the 'Payload' card would be weird.

Instead, what I think should be done is to open an Issue on the [r/SpaceX API GitHub page](https://github.com/r-spacex/SpaceX-API), for the maintainer to notice that there's a future launch, with no payload attached to it.

What do you think about it?

**Comment by bahaafathi** [comment]
You're right displaying empty data is weird. but less weird than the red page and it's a  temporary solution, I've open an Issue on the **SpaceX API**  to solve this problem,

**Comment by bahaafathi** [comment]
###  problem solved by SpaceX API

**Comment by jesusrp98** [comment]
Nice! Thank you very much for noticing this!
Closing the issue.
