### ISSUE TITLE
Contrast in SearchBar/TopBar in light theme 

### ISSUE THREAD

**Issue by deandreamatias** [jesusrp98/spacex-go#35]
## Environment

**SpaceX Go Version:**  2.4.0 - better-ux
**Android Version:** 8.0 
**Device Information:**  
- Manufacturer: Huawei
- Model: P10 Lite  
---

## Description

**Expected behavior**:
When using the search function, in the search field, have a contrast between the word 'search' and the field.
**Current behavior**:
Don't have a contrast.

## Steps to reproduce

1. Go to settings.
1. Select the light theme
1. Return to Home
1. Select the Vehicle, Upcoming or Lastest Tab.
1. Press Search FAB
1. Look the contrast

**Images**: 
![photo5032814206570833972](https://user-images.githubusercontent.com/21011641/56796706-69310b80-6813-11e9-852f-3069a0a8edfb.jpg)

**Comment by jesusrp98** [comment]
Since I'm using the `material_search` package, and it doesn't allow to change the textbox's color, I can't do anything to fix this issue.

Fortunately, I've been planning to update the search screen for a while now. I'm planning to add more filter options, and of course, fix this issue as well.

This new search screen is planned for the June-July update.

**Comment by jesusrp98** [comment]
Finally, I have the time to take a look at this issue.

I'm building a new component, extending the [SeachDelegate](https://api.flutter.dev/flutter/material/SearchDelegate-class.html) class from the Flutter framework, which will allow me to implement a more customized search experience.

One thing I wanted to add is new filtering options. At first, I wanted to add another screen where the user would be allow to select launch year & vehicle etc, but then I thought that building this functionality into the search bar itself may be a better idea. So now the user will be able to write `2019` or `Falcon Heavy` in the text field itself.

Building this new search experience will allow me to fix this issue itself as well :)

This feature is being develop in the [`search`](https://github.com/jesusrp98/spacex-go/tree/search) branch, and should be available to all users in the v2.7 update, hopefully launching this next month.

**Comment by jesusrp98** [comment]
After some months of work, this feature is now implemented in the v2.7 update!

You can now filter by mission name or launch vehicle, and on the vehicle side by name or maiden launch year.

The UI now tells the user these new filter options. Contrast bugs have also been fixed, since I'm now using the `SearchDelegate` method from the Flutter framework.
