### ISSUE TITLE
[SpacexGo][v2.3.0]Problem in search bar color and fonts color.

### ISSUE THREAD

**Issue by masudr4n4** [jesusrp98/spacex-go#36]
<h4>Actual Behaviour</h4>
The search color and the fonts color are same thats why hard to read or see what i have written.
<h4>Expected Behaviour </h4>
I expected that the font will be in other color rather than search bar color
<h4>Step to reproduce </h4>
<ol>
<li>install and open the app</li>
<li>From home page ,click the three horizontal dots then click settings(its dark mode as default)</li>
<li>disable dark mode and click back</li>
<li>now click search icon to search</li>
<li>type something and see how hard to read what you have written to search bar.</li>
</ol>
<h4>Information </h4>
<ul>
<li>App version:v2.3.0</li>
<li>Os:Android 9.0</li>
<li>Device:Samsung A10</li>
</ul>
<h4>Recording of the bug</h4>
<a href="https://youtu.be/rg_o8_jGGpA">https://youtu.be/rg_o8_jGGpA</a>

**Comment by deandreamatias** [comment]
Hi @maaudrana, thanks for your report!
This issue is already described in #35. But I will change the title of the other issue to avoid problems in the future.
Thanks

**Comment by jesusrp98** [comment]
Hey, thanks for taking the time to report this bug!

As @deandreamatias said, this issue has been already reported. The problem lays on the package that I'm using at this moment, to implement the search functionality.

I'm planning to implement a much better search functionality, with more filter options in the future. This feature is planned for July, since at this moment I don't the time necessary to implement this kind of feature.

**Comment by jesusrp98** [comment]
Closing this issue, because it's duplicated.

See #35.
