### ISSUE TITLE
Not sure how to describe this (dev branch)

### ISSUE THREAD

**Issue by DitchDoctors** [jesusrp98/spacex-go#70]
I was playing with the app earlier and the master branch worked perfect on my android virtual device then i switched to the dev branch and this happened. It happens on a real ios device as well. I didnt change anything in these examples. I dont know if its a real issue or if im just dumb so I thought Id share :)
<img width="202" alt="Capture" src="https://user-images.githubusercontent.com/50470266/68995866-28085380-0858-11ea-8231-33817e3f1289.PNG">
![IMG_0248](https://user-images.githubusercontent.com/50470266/68995873-3ce4e700-0858-11ea-9f47-46bf63ab29f1.PNG)

Edit: debug console only shows this 
<img width="701" alt="Capture" src="https://user-images.githubusercontent.com/50470266/68995913-a2d16e80-0858-11ea-8190-7a2cb19d51b3.PNG">

**Comment by jesusrp98** [comment]
Found this exact bug when updated all project dependencies. This is an issue of the translation package.

Opened an [issue](https://github.com/ilteoood/flutter_i18n/issues/54) a couple minutes later, and it seems it has been fixed in the v0.8.2 update.

Pull all the changes I've doing since, simply `git pull` :)

**Comment by DitchDoctors** [comment]
Oh, I'm sorry for bothering you. Thanks! Ill try it after a nap.

post-nap edit: Worked :)
